import {config as c} from './config.js';
const $=s=>document.querySelector(s), money=n=>'¥'+n.toLocaleString('ja-JP');
const escape=s=>String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const safeUrl=url=>{try{const u=new URL(url);return u.protocol==='https:'?u.href:null}catch{return null}};
const external=url=>c.previewMode?null:safeUrl(url);
document.querySelectorAll('[data-brand]').forEach(el=>el.textContent=c.brand);document.querySelectorAll('[data-service]').forEach(el=>el.textContent=c.service);document.querySelectorAll('[data-name]').forEach(el=>el.textContent=c.name);document.querySelectorAll('[data-days]').forEach(el=>el.textContent=c.replyDays);document.title=`${c.previewMode?'【確認用】 ':''}${c.brand} — ${c.service}`;$('#preview-banner').hidden=!c.previewMode;$('#year').textContent=new Date().getFullYear();$('#profile-text').textContent=c.profile;$('#english-name').textContent=c.englishName;$('#awards').innerHTML=c.awards.map(a=>`<li>${escape(a)}</li>`).join('');$('#storage-period').textContent=c.storagePeriod;$('#membership').hidden=!c.membershipEnabled;
if(c.profilePhoto){$('#profile-visual img').src=c.profilePhoto;$('#profile-visual img').alt=c.name+'のプロフィール写真';$('#profile-visual p').hidden=true;}
$('#campaign').hidden=!c.campaign.enabled;$('#campaign b').textContent=c.campaign.title;$('.campaign-tag').textContent=`先着${c.campaign.places}名限定`;$('#campaign-price').textContent=`${c.campaign.minutes}分以内 / ${money(c.campaign.price)}`;
$('#plan-grid').innerHTML=c.plans.map((p,i)=>`<article class="plan ${i===1?'recommended':''}">${i===1?'<span class="recommended-tag">RECOMMENDED</span>':''}<span class="eyebrow">PLAN 0${i+1}</span><h3>${escape(p.name)}</h3><p class="description">${escape(p.description)}</p><div class="price">${money(p.price)}<small>/ 1回</small></div><ul><li>演奏動画 ${p.minutes}分以内</li><li>質問 ${p.questions}つまで</li><li>${p.characters}字以上を目安にお届け</li></ul><button class="button ${i===1?'':'outline'}" data-plan="${escape(p.id)}">このプランを申し込む <span>↗</span></button></article>`).join('');
$('#option-list').innerHTML=c.options.map(o=>`<p>${escape(o.name)} <b>＋${money(o.price)}</b></p>`).join('');$('#form-plan').innerHTML=c.plans.map(p=>`<option value="${escape(p.id)}">${escape(p.name)}</option>`).join('')+(c.campaign.enabled?'<option value="campaign">Opening Trial</option>':'');
const faqs=[['顔を映す必要はありますか？','ありません。手元だけ、鍵盤だけの動画でもご利用いただけます。'],['本名を出したくありません。','ニックネームでお申し込みいただけます。'],['スマートフォンで撮った動画でも大丈夫ですか？','はい。演奏が確認できる音質・画質であれば問題ありません。'],['先生についていますが利用できますか？','はい。現在の先生の指導を否定・変更するものではなく、一人のピアニストからの別の視点としてご利用ください。'],['どんなレベルでも利用できますか？','初心者から専門的に学んでいる方までご利用いただけます。'],['何日で返信されますか？',`原則として受付から${c.replyDays}以内を予定しています。`],['動画は公開されますか？','本人の許可なくSNS、YouTube等で演奏動画を公開することはありません。'],['送った動画はどうなりますか？',`フィードバックのためにのみ使用し、一定期間後に削除する方針です。保存期間は${c.storagePeriod}`]];$('#faq-list').innerHTML=faqs.map(([q,a])=>`<details><summary><b>${escape(q)}</b><span>＋</span></summary><p>${escape(a)}</p></details>`).join('');
$('#menu').onclick=()=>{const open=$('nav').classList.toggle('open');$('#menu').setAttribute('aria-expanded',open);$('#menu').setAttribute('aria-label',open?'メニューを閉じる':'メニューを開く');};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{$('nav').classList.remove('open');$('#menu').setAttribute('aria-expanded','false')});
const dialog=$('#apply-dialog');$('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
function openPlan(p){$('#dialog-title').textContent=p.name||'Opening Trial';$('#dialog-content').innerHTML=`<p>${p.minutes}分以内の演奏動画 / ${money(p.price)}</p><div>${c.options.map(o=>`<label><input type="checkbox" data-option="${o.id}"> ${escape(o.name)} ＋${money(o.price)}</label>`).join('')}</div><p class="dialog-total">合計 <span>${money(p.price)}</span></p><p class="status-note">${external(p.squareUrl)?'Squareの決済ページへ進みます。決済完了後、このサイトの動画提出フォームをご利用ください。':'現在は公開準備中です。Square決済リンクが設定されるまで、お申し込み・お支払いはできません。'}</p><button type="button" id="checkout" class="button">${external(p.squareUrl)?'Square決済へ進む ↗':'閉じてプランに戻る'}</button><p class="fine">オプション選択は見積りです。Square側で同じプラン・オプションと合計金額を選び、ご確認ください。</p>`;$('#dialog-content').querySelectorAll('[data-option]').forEach(input=>input.onchange=()=>{let total=p.price;$('#dialog-content').querySelectorAll('[data-option]:checked').forEach(i=>total+=c.options.find(o=>o.id===i.dataset.option).price);$('.dialog-total span').textContent=money(total)});$('#checkout').onclick=()=>{const url=external(p.squareUrl);if(url)window.location.assign(url);else dialog.close()};$('#form-plan').value=p.id||'campaign';dialog.showModal();}
document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>openPlan(c.plans.find(p=>p.id===b.dataset.plan)));$('#campaign').onclick=e=>{e.preventDefault();openPlan({...c.campaign,name:'Opening Trial',id:'campaign'})};
document.querySelectorAll('[name=videoMethod]').forEach(input=>input.onchange=()=>{const url=input.value==='url';$('#url-fields').hidden=!url;$('#dropbox-fields').hidden=url;$('[name=videoUrl]').required=url;$('[name=uploaded]').required=!url;});$('#upload').onclick=()=>{const url=external(c.dropboxUrl);if(url)window.open(url,'_blank','noopener,noreferrer');else $('#form-status').textContent='アップロード先は未設定です。正式受付開始までお待ちください。'};
$('#submission-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(data.videoMethod==='url'&&!safeUrl(data.videoUrl)){ $('#form-status').textContent='動画URLには https:// で始まるアドレスを入力してください。';return}$('#dialog-title').textContent='入力内容の確認';const names={nickname:'ニックネーム',email:'メールアドレス',piece:'曲名 / 作曲者',plan:'プラン',videoUrl:'動画URL',focus:'聴いてほしいこと',experience:'演奏歴',teacher:'先生について',event:'本番の予定',passage:'気になる箇所',other:'その他質問'};$('#dialog-content').innerHTML=Object.entries(names).filter(([k])=>data[k]).map(([k,v])=>`<div class="review-row"><b>${v}</b><span>${escape(k==='plan'?$('#form-plan').selectedOptions[0].textContent:data[k])}</span></div>`).join('')+(data.videoMethod==='dropbox'?'<p>動画：Dropboxアップロード完了（申告）</p>':'')+`<p class="status-note">${external(c.formEndpoint)?'内容をご確認のうえ、送信してください。':'現在は公開準備中のため、入力内容は送信・保存されていません。受付開始後に改めてご提出ください。'}</p><button id="confirm-submit" type="button" class="button">${external(c.formEndpoint)?'この内容で送信する ↗':'入力に戻る'}</button>`;$('#confirm-submit').onclick=async()=>{if(!external(c.formEndpoint)){dialog.close();return}const button=$('#confirm-submit');button.disabled=true;button.textContent='送信中…';try{const response=await fetch(c.formEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!response.ok)throw new Error();dialog.close();$('#form-status').textContent='送信が完了しました。フィードバックの受付確認メールをお待ちください。';$('#submission-form').reset();$('#url-fields').hidden=false;$('#dropbox-fields').hidden=true;$('[name=videoUrl]').required=true;$('[name=uploaded]').required=false;}catch{button.disabled=false;button.textContent='再度送信する';$('.status-note').textContent='送信できませんでした。入力内容は保持されています。時間を置いてお試しください。'}};dialog.showModal();};
